# Generated by Django 5.0.13 on 2025-12-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_Viajes',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id_alojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=255)),
                ('tipo_alojamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('estrellas', models.IntegerField(blank=True, null=True)),
                ('precio_noche_estandar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_incluidos', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Viajes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('preferencias_viaje', models.TextField(blank=True, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('continente', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('atracciones_principales', models.TextField(blank=True, null=True)),
                ('clima', models.CharField(blank=True, max_length=50, null=True)),
                ('divisa_local', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('num_vuelo', models.CharField(max_length=20)),
                ('aerolinea', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('precio_clase_economica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asientos_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete_Turistico',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paquete', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_adulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nino', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cupo_maximo', models.IntegerField()),
                ('incluye_vuelo', models.BooleanField(default=False)),
                ('incluye_alojamiento', models.BooleanField(default=False)),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agencia_de_viajes.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Viaje',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('num_adultos', models.IntegerField()),
                ('num_ninos', models.IntegerField(blank=True, default=0, null=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_reserva', models.CharField(max_length=50)),
                ('fecha_vencimiento_pago', models.DateField(blank=True, null=True)),
                ('id_agente_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_agencia_de_viajes.agente_viajes')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agencia_de_viajes.cliente_viajes')),
                ('id_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agencia_de_viajes.paquete_turistico')),
            ],
        ),
    ]
