# Generated by Django 5.0.13 on 2025-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia_de_viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_viajes',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva_viaje',
            name='fecha_reserva',
            field=models.DateTimeField(),
        ),
    ]
