# Generated by Django 5.0.13 on 2025-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia_de_viajes', '0002_alter_cliente_viajes_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_viajes',
            name='id_agente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='id_alojamiento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente_viajes',
            name='id_cliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destino',
            name='id_destino',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paquete_turistico',
            name='id_paquete',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva_viaje',
            name='estado_reserva',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva_viaje',
            name='id_reserva',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='id_vuelo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
